name : receive for master

on:
  repository_dispatch:
    types: [new-version-available-master]

jobs:
  send_version:
    runs-on: ubuntu-latest
    steps:
      - name: install yq
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
          sudo add-apt-repository ppa:rmescandon/yq -y
          sudo apt update -y
          sudo apt install yq -y

      - uses: actions/checkout@v2

      - name: Update Version
        run: |
          git config --global user.name 'Github'
          git config --global user.email 'github@users.noreply.github.com'
          
          yq w --inplace config/properties.yml 'app.version.tag' "${{ github.event.client_payload.version }}"

          git add config/properties.yml
          git diff-index --quiet HEAD || git commit -m "[Auto] version updated to ${{ github.event.client_payload.version }}"
          git push
      
